DROP DATABASE Tut3;
CREATE DATABASE Tut3;

USE Tut3;

CREATE TABLE EMPLOYEE (
    EID INT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Supervisor_ID INT,
    FOREIGN KEY (Supervisor_ID) REFERENCES EMPLOYEE(EID) ON DELETE SET NULL,
    Constraint chk1 CHECK (Supervisor_ID IS NULL OR EID <> Supervisor_ID) /*does not work on my system for some reason. Throws error. Some verison issue*/
);

CREATE TABLE DEPARTMENT (
    DNO INT PRIMARY KEY, 
    Name VARCHAR(50) NOT NULL,
    Manager_ID INT NOT NULL UNIQUE,
    Start_Date DATE NOT NULL,
    FOREIGN KEY (Manager_ID) REFERENCES EMPLOYEE(EID) ON DELETE RESTRICT
);

CREATE TABLE DEPT_LOCATIONS (
    DNO INT, 
    Loc VARCHAR(50), /*should this be unique??*/
    PRIMARY KEY (DNO, Loc),
    FOREIGN KEY (DNO) REFERENCES DEPARTMENT(DNO) ON DELETE CASCADE
);

CREATE TABLE PROJECT (
    PNO INT PRIMARY KEY,
    Name VARCHAR(50) NOT NULL,
    Ploc VARCHAR(50) NOT NULL,
    Dept_in_charge INT NOT NULL,
    FOREIGN KEY (Dept_in_charge) REFERENCES DEPARTMENT(DNO) ON DELETE CASCADE
);

CREATE TABLE Works_On (
    EID INT,
    PNO INT,
    Hours DECIMAL(5,2) NOT NULL CHECK (Hours BETWEEN 10 AND 40),
    PRIMARY KEY (EID,PNO),
    FOREIGN KEY (EID) REFERENCES EMPLOYEE(EID) ON DELETE CASCADE,
    FOREIGN KEY (PNO) REFERENCES PROJECT(PNO) ON DELETE CASCADE
);

